name: JS Actions

on:
  # Run when an issue is labeled
  #issues:
  #  types: [labeled]
  # Run when a PR is opened
  pull_request:
    types: [opened]

jobs:
  joke-action:
    # Actions are disabled on the original template
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: hilarity-ensues
        uses: ./.github/actions/joke-action       
      - run:  gh pr comment $PR_URL --body INPUT_{"joke-output"}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}     
