name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  joke-action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: hilarity-ensues
        uses: ./.github/actions/joke-action
        id: joke

  issue-joke:
    name: Comment
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: issue-joke
        uses: peter-evans/create-or-update-comment@v2
        env:
          NEW_JOKE: ${{ steps.hilarity-ensues.outputs.stdout }}
        with:        
          issue-number: ${{ github.event.issue.number }}
          body: |
            $NEW_JOKE
