name: JS Actions

on:
  # Run when an issue is labeled
  #issues:
  #  types: [labeled]
  # Run when a PR is opened
  pull-request:
    types: [opened]

jobs:
  joke-action:
    # Actions are disabled on the original template
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: hilarity-ensues
        uses: ./.github/actions/joke-action
        id: joke

  issue-joke:
    name: joke-comment
    runs-on: ubuntu-latest
    permissions:
      # Give issue write access
      #issues: write
      # Give PR write access
      pull-requests: write
    steps:
      - name: issue-joke
      - run: gh pr comment $PR_URL --body $NEW_JOKE
        env:
          NEW_JOKE: ${{ steps.hilarity-ensues.outputs.stdout }}
        #with:     
          #issue-number: ${{ github.event.issue.number }}
          #body: |
            #run: echo $NEW_JOKE
