name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  joke-action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - name: hilarity-ensues
      - uses: actions/checkout@v3
        uses: ./.github/actions/joke-action

  issue-joke:
    name: Comment
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Automatic Comment
        uses: peter-evans/create-or-update-comment@v2
        with:        
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for labelling an issue! We have received it and will follow up with you soon.        
